spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      open-in-view: false
  mail:
    host: smtp.gmail.com # 1
    port: 587 # 2
    username: ${mail.username} # 3
    password: ${mail.password} # 4
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  output:
    ansi:
      enabled: always
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
  #org.springframework.security: trace